'use client';
import { useCallback,useEffect,useState } from 'react';
import ContentImageManager from './content-image-manager.js';

const configs={
 destinations:{label:'Destinations',fields:[['slug','URL slug','text',true],['name_en','Name · English','text',true],['name_hi','Name · Hindi','text'],['summary_en','Summary · English','textarea'],['summary_hi','Summary · Hindi','textarea'],['description_en','Description · English','textarea'],['description_hi','Description · Hindi','textarea'],['state_name','State','text'],['district_name','District','text'],['latitude','Latitude','number'],['longitude','Longitude','number'],['best_time_en','Best time · English','text'],['best_time_hi','Best time · Hindi','text']]},
 attractions:{label:'Attractions',fields:[['destination_id','Destination ID','text',true],['slug','URL slug','text',true],['name_en','Name · English','text',true],['name_hi','Name · Hindi','text'],['description_en','Description · English','textarea'],['description_hi','Description · Hindi','textarea'],['category','Category','text'],['latitude','Latitude','number'],['longitude','Longitude','number'],['visiting_hours','Visiting hours','text'],['entry_fee_note','Entry fee note','text'],['source_url','Source URL','url'],['verified_at','Verified date','date']]},
 articles:{label:'Articles',fields:[['slug','URL slug','text',true],['title_en','Title · English','text',true],['title_hi','Title · Hindi','text'],['excerpt_en','Excerpt · English','textarea'],['excerpt_hi','Excerpt · Hindi','textarea'],['body_en','Body · English','textarea'],['body_hi','Body · Hindi','textarea'],['author_name','Author name','text'],['seo_title_en','SEO title · English','text'],['seo_title_hi','SEO title · Hindi','text'],['seo_description_en','SEO description · English','textarea'],['seo_description_hi','SEO description · Hindi','textarea']]},
};
const statuses=['DRAFT','REVIEW','PUBLISHED','ARCHIVED'];

export default function ContentManager({type,role}){
 const config=configs[type];
 const [rows,setRows]=useState([]),[pagination,setPagination]=useState({page:1,total:0,totalPages:0}),[page,setPage]=useState(1),[q,setQ]=useState(''),[status,setStatus]=useState(''),[selected,setSelected]=useState(null),[form,setForm]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const refresh=useCallback(async()=>{setBusy(true);setError('');try{const params=new URLSearchParams({page:String(page),limit:'20',...(q?{q}:{}),...(status?{status}:{})});const res=await fetch(`/api/admin/${type}?${params}`,{cache:'no-store'});const payload=await res.json();if(!res.ok)throw new Error(payload.error||'Could not load content');setRows(payload.data);setPagination(payload.pagination);}catch(err){setError(err.message||'Could not load content');}finally{setBusy(false);}},[type,page,q,status]);
 useEffect(()=>{void refresh();},[refresh]);
 function newRecord(){setSelected(null);setForm({});setError('');setNotice('');}
 function editRecord(row){setSelected(row);setForm(Object.fromEntries(config.fields.map(([name])=>[name,row[name]??''])));setError('');setNotice('');}
 async function save(event){event.preventDefault();setBusy(true);setError('');setNotice('');try{const payload={};for(const [key,value] of Object.entries(form)){if(value==='')continue;const def=config.fields.find(([name])=>name===key);payload[key]=def?.[2]==='number'?Number(value):value;}const res=await fetch(`/api/admin/${type}${selected?`/${selected.id}`:''}`,{method:selected?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const result=await res.json();if(!res.ok)throw new Error(result.error||'Could not save changes');setNotice(selected?'Changes saved.':'Draft created.');setSelected(result.data);setForm(Object.fromEntries(config.fields.map(([name])=>[name,result.data[name]??''])));await refresh();}catch(err){setError(err.message||'Could not save changes');}finally{setBusy(false);}}
 async function changeStatus(next){if(!selected)return;const verb=next==='PUBLISHED'?'publish':next==='DRAFT'&&selected.status==='PUBLISHED'?'unpublish':next==='ARCHIVED'?'archive':'move';if(!window.confirm(`Are you sure you want to ${verb} this ${type.slice(0,-1)}?`))return;setBusy(true);setError('');try{const res=await fetch(`/api/admin/${type}/${selected.id}/status`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status:next})});const result=await res.json();if(!res.ok)throw new Error(result.error||'Status change failed');setSelected(result.data);setNotice(`Status changed to ${next.toLowerCase()}.`);await refresh();}catch(err){setError(err.message||'Status change failed');}finally{setBusy(false);}}
 if(!config)return <p className="error">Unknown content type.</p>;
 return <section className="manager-grid"><div className="list-panel"><div className="list-toolbar"><label className="search-label">Search<input value={q} onChange={(e)=>{setPage(1);setQ(e.target.value);}} placeholder="Search records" maxLength={100}/></label><label className="filter-label">Status<select value={status} onChange={(e)=>{setPage(1);setStatus(e.target.value);}}><option value="">All status</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><button className="button primary" onClick={newRecord}>New draft</button></div>
 {error&&!selected&&<p className="error" role="alert">{error}</p>}{busy&&!rows.length?<p className="loading">Loading {config.label.toLowerCase()}…</p>:rows.length===0?<div className="empty"><span>✦</span><h2>No {config.label.toLowerCase()} found</h2><p>Try another search or create a new draft.</p></div>:<div className="record-list">{rows.map(row=><button key={row.id} className={`record-row ${selected?.id===row.id?'active':''}`} onClick={()=>editRecord(row)}><span><b>{row.name_en||row.title_en||row.slug}</b><small>{row.slug}</small></span><span className={`status status-${row.status?.toLowerCase()}`}>{row.status}</span></button>)}</div>}
 <div className="pagination"><span>{pagination.total} records</span><div><button className="button subtle" disabled={page<=1||busy} onClick={()=>setPage(page-1)}>Previous</button><span>Page {pagination.page||page} of {pagination.totalPages||1}</span><button className="button subtle" disabled={page>=pagination.totalPages||busy} onClick={()=>setPage(page+1)}>Next</button></div></div></div>
 <div className="editor-panel"><div className="editor-heading"><div><p className="eyebrow">{selected?'EDIT RECORD':'NEW CONTENT'}</p><h2>{selected?(selected.name_en||selected.title_en||selected.slug):`Create ${config.label.slice(0,-1).toLowerCase()}`}</h2></div>{selected&&<span className={`status status-${selected.status?.toLowerCase()}`}>{selected.status}</span>}</div>
 {error&&selected&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success" role="status">{notice}</p>}
 <form className="editor-form" onSubmit={save}><div className="field-grid">{config.fields.map(([name,label,kind,required])=><label key={name} className={kind==='textarea'?'span-two':''}>{label}{kind==='textarea'?<textarea rows={3} value={form[name]||''} required={required} maxLength={50000} onChange={e=>setForm({...form,[name]:e.target.value})}/>:<input type={kind} value={form[name]||''} required={required} maxLength={kind==='url'?2048:10000} step={kind==='number'?'any':undefined} onChange={e=>setForm({...form,[name]:e.target.value})}/>}</label>)}</div>
 <button className="button primary" disabled={busy}>{busy?'Saving…':selected?'Save changes':'Create draft'}</button></form>
 {selected && (type === 'destinations' || type === 'attractions' || type === 'articles') && <ContentImageManager type={type} slug={selected.slug} />}
 {selected&&<div className="workflow"><h3>Editorial workflow</h3><p>Current status: <strong>{selected.status}</strong></p><div className="workflow-actions">{selected.status==='DRAFT'&&<button className="button" disabled={busy} onClick={()=>changeStatus('REVIEW')}>Submit for review</button>}{role==='admin'&&selected.status==='REVIEW'&&<><button className="button" disabled={busy} onClick={()=>changeStatus('DRAFT')}>Return to draft</button><button className="button primary" disabled={busy} onClick={()=>changeStatus('PUBLISHED')}>Publish</button></>}{role==='admin'&&selected.status==='PUBLISHED'&&<button className="button" disabled={busy} onClick={()=>changeStatus('DRAFT')}>Unpublish</button>}{role==='admin'&&selected.status!=='ARCHIVED'&&<button className="button danger" disabled={busy} onClick={()=>changeStatus('ARCHIVED')}>Archive</button>}{role==='admin'&&selected.status==='ARCHIVED'&&<button className="button" disabled={busy} onClick={()=>changeStatus('DRAFT')}>Restore to draft</button>}</div><small>Actions are recorded in the administrative audit history.</small></div>}
 </div></section>;
}
