'use client';
import { useCallback,useEffect,useState } from 'react';

export default function MediaLibrary(){
 const [items,setItems]=useState([]),[q,setQ]=useState(''),[page,setPage]=useState(1),[pagination,setPagination]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{setBusy(true);setError('');try{const params=new URLSearchParams({page:String(page),limit:'20',...(q?{q}:{})});const res=await fetch(`/api/admin/media?${params}`,{cache:'no-store'});const body=await res.json();if(!res.ok)throw new Error(body.error||'Media library is unavailable');setItems(body.data);setPagination(body.pagination);}catch(e){setError(e.message||'Media library is unavailable');}finally{setBusy(false);}},[page,q]);
 useEffect(()=>{void load();},[load]);
 async function upload(event){event.preventDefault();const form=event.currentTarget;const file=form.elements.image.files?.[0];if(!file)return;setError('');setNotice('');if(file.size>5*1024*1024){setError('Image must be 5 MB or smaller.');return;}if(!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type)){setError('Choose a JPEG, PNG, WebP or AVIF image.');return;}setBusy(true);try{const res=await fetch('/api/admin/media/upload',{method:'POST',headers:{'content-type':'application/octet-stream'},body:file});const body=await res.json();if(!res.ok)throw new Error(body.error||'Upload failed');setNotice('Image uploaded and added to the media library.');form.reset();await load();}catch(e){setError(e.message||'Upload failed');}finally{setBusy(false);}}
 async function saveMetadata(event,id){event.preventDefault();const form=new FormData(event.currentTarget);const data=Object.fromEntries(['alt_en','alt_hi','credit','license'].map(k=>[k,String(form.get(k)||'').trim()||null]));setBusy(true);setError('');try{const res=await fetch(`/api/admin/media/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(data)});const body=await res.json();if(!res.ok)throw new Error(body.error||'Could not save media details');setNotice('Media details saved.');await load();}catch(e){setError(e.message||'Could not save media details');}finally{setBusy(false);}}
 return <div className="media-page"><div className="media-upload"><div><h2>Add an image</h2><p>JPEG, PNG, WebP or AVIF · maximum 5 MB. Storage access is controlled by Supabase policies.</p></div><form onSubmit={upload}><input name="image" type="file" accept="image/jpeg,image/png,image/webp,image/avif" required/><button className="button primary" disabled={busy}>{busy?'Working…':'Upload image'}</button></form></div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success" role="status">{notice}</p>}
 <div className="list-toolbar media-toolbar"><label className="search-label">Search assets<input value={q} onChange={e=>{setPage(1);setQ(e.target.value);}} placeholder="Path, alt text or credit" maxLength={100}/></label></div>
 {busy&&!items.length?<p className="loading">Loading media…</p>:items.length===0?<div className="empty"><span>✦</span><h2>No media assets yet</h2><p>Upload a verified image after the storage bucket and permissions are configured.</p></div>:<div className="media-grid">{items.map(item=><article className="media-card" key={item.id}><div className="media-preview">{item.public_url?<img src={item.public_url} alt={item.alt_en||''}/>:<span>Image asset</span>}</div><p className="asset-path">{item.storage_path}</p><form onSubmit={e=>saveMetadata(e,item.id)} className="metadata-form">{[['alt_en','Alt text · English'],['alt_hi','Alt text · Hindi'],['credit','Credit'],['license','License']].map(([name,label])=><label key={name}>{label}<input name={name} defaultValue={item[name]||''} maxLength={1000}/></label>)}<button className="button" disabled={busy}>Save details</button></form></article>)}</div>}
 <div className="pagination"><span>{pagination.total||0} assets</span><div><button className="button subtle" disabled={page<=1||busy} onClick={()=>setPage(page-1)}>Previous</button><span>Page {pagination.page||page} of {pagination.totalPages||1}</span><button className="button subtle" disabled={page>=(pagination.totalPages||1)||busy} onClick={()=>setPage(page+1)}>Next</button></div></div></div>;
}
